# Generated by Django 4.2.7 on 2023-11-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/default_course_image.png', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
